on: 
  push:
      branches:
        - main

steps:
  id: deploy
  uses: google-github-actions/deploy-cloud-functions@main
  with:
    name: function-1
    runtime: ruby26
    credentials: ${{ secrets.gcp_credentials }}